Models/ErrorViewModel.cs
namespace AluguelDeCasas.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/ReservaPendenteModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AluguelDeCasas.Models
{
	public class ReservaPendenteModel
	{

		public int Id { get; set; }

		public string NOME { get; set; }

		public string CONTATO { get; set; }

		public string TIPO_EVENTO { get; set; }

		public string PAGAMENTO { get; set; }

		public string SERVICOS_ADD { get; set; }

		public string DIA_ENTRADA { get; set; }

		public string DIA_SAIDA { get; set; }
	}
}

Models/UsuarioCliente.cs
namespace AluguelDeCasas.Models
{
	public class UsuarioCliente
	{
		public int ID { get; set; }
		public string NOME { get; set; }
		public string USUARIO { get; set; }
		public string SENHA { get; set; }
	}
}

Controllers/AdministradorController.cs
using AluguelDeCasas.Models;
using AluguelDeCasas.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace AluguelDeCasas.Controllers
{
	public class AdministradorController : Controller
	{
		public IActionResult Index(string validate)
		{
			if (validate == "true") {

				return View();
			}
			else
			{
				var result = new
				{
					Success = false,
					Message = "NÃO PERMITIDO",
					Codigo = "404"
				};
				return View("~/Views/Login/Index.cshtml");
			}

		}

		private readonly IReservaPendenteRepositorio _reservaPendenteRepositorio;
		public AdministradorController(IReservaPendenteRepositorio reservaPendenteRepositorio)
		{
			_reservaPendenteRepositorio = reservaPendenteRepositorio;

		}

		public IActionResult BuscarEditar(int id)
		{
			ReservaPendenteModel reserva = _reservaPendenteRepositorio.BuscarEditar(id);
			return new JsonResult(reserva);
		}

		public IActionResult BuscarEditarAprovados(int id)
		{
			ReservaPendenteModel reserva = _reservaPendenteRepositorio.BuscarAprovados(id);
			return new JsonResult(reserva);
		}

		public IActionResult ListarReservasPendentes()
		{
			List<ReservaPendenteModel> reserva = _reservaPendenteRepositorio.ListarTodasReservasPendentes();
			return new JsonResult(reserva);
		}

		public IActionResult ExcluirSolicitacaoDeReserva(int id)
		{
			_reservaPendenteRepositorio.Excluir(id);
			var result = new
			{
				Success = true,
				Message = "Excluido com sucesso",
				Codigo = "0"
			};
			return Json(result);
		}

		public IActionResult IncluirReserva(ReservaPendenteModel reserva)
		{
			_reservaPendenteRepositorio.AprovarReserva(reserva);
			var result = new
			{
				Success = true,
				Message = "Aprovado com sucesso!",
				Codigo = "0"
			};
			return Json(result);
		}

		public IActionResult ListarReservasAprovadas()
		{
			List<ReservaPendenteModel> reserva = _reservaPendenteRepositorio.ListarTodasReservas();
			return new JsonResult(reserva);
		}

		public IActionResult AlterarReserva(ReservaPendenteModel reserva)
		{
			_reservaPendenteRepositorio.AlterarReserva(reserva);
			return RedirectToAction("Index");
		}

		public IActionResult ExcluirReserva(int id)
		{
			_reservaPendenteRepositorio.ExcluirReservaAprovada(id);
			var result = new
			{
				Success = true,
				Message = "Reserva excluida com sucesso",
				Codigo = "0"
			};
			return Json(result);
		}


	}

}

Controllers/AgendaController.cs
using AluguelDeCasas.Models;
using AluguelDeCasas.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace AluguelDeCasas.Controllers
{
	public class AgendaController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		private readonly IReservaPendenteRepositorio _reservaPendenteRepositorio;
		public AgendaController(IReservaPendenteRepositorio reservaPendenteRepositorio)
		{
			_reservaPendenteRepositorio = reservaPendenteRepositorio;

		}

		[HttpPost]
		public IActionResult IncluirSolicitacao(ReservaPendenteModel reserva)
		{
			_reservaPendenteRepositorio.Adicionar(reserva);
			return RedirectToAction("Index");
		}

	}
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace AluguelDeCasas.Controllers
{
	public class ContatoController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/FotoController.cs
using Microsoft.AspNetCore.Mvc;

namespace AluguelDeCasas.Controllers
{
	public class FotoController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/HomeController.cs
using AluguelDeCasas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AluguelDeCasas.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/LoginController.cs
using AluguelDeCasas.Models;
using AluguelDeCasas.Repositorio;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AluguelDeCasas.Controllers
{
	public class LoginController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		private readonly IReservaPendenteRepositorio _reservaPendenteRepositorio;
		public LoginController(IReservaPendenteRepositorio reservaPendenteRepositorio)
		{
			_reservaPendenteRepositorio = reservaPendenteRepositorio;

		}

		public IActionResult ValidarLoginAutenticado(string user, string psw)
		{
			UsuarioCliente loginUsuario = _reservaPendenteRepositorio.ValidarLoginAutenticado(user, psw);

			if (loginUsuario == null)
			{
				var result = new
				{
					Success = false,
					Message = "ACESSO NEGADO",
					Codigo = "0"
				};
				return Json(result);
			}

			else {
				var userBda = loginUsuario.USUARIO;
				var pswBda = loginUsuario.SENHA;
				if (user == userBda) {
					if (psw == pswBda) {
						var result = new
						{
							Success = true,
							Message = "ACESSO PERMITIDO",
							Codigo = "0"
						};
						return Json(result);
					}
					else
					{
						var result = new
						{
							Success = false,
							Message = "ACESSO NEGADO",
							Codigo = "0"
						};
						return Json(result);
					}
				}
				else
				{
					var result = new
					{
						Success = false,
						Message = "ACESSO NEGADO",
						Codigo = "0"
					};
					return Json(result);
				}
			}

		}

	}
}

Controllers/ServicosController.cs
using Microsoft.AspNetCore.Mvc;

namespace AluguelDeCasas.Controllers
{
	public class ServicosController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Inicio";
}


<html>

<head>
	<!-- Icon nav bar -->
	<link rel="shortcut icon" href="~/css/img/icone-site.png" type="image/x-icon">

	<title>Home</title>
</head>
<body id="body-home-page">

	<!-- MENU DESKTOP -->
	<nav class="navbar navbar-expand-lg navbar-custom">
		<div class="container-fluid">

			<a class="navbar-brand" href="@Url.Action("Index", "Home")">
				<img id="logo-home" src="~/css/img/sua-logo-aqui.png" />
			</a>

			<div class="collapse navbar-collapse" id="navbarNavMenu">
				<ul class="navbar-nav ms-auto">
					<li class="nav-item active">
						<a class="nav-link" href="@Url.Action("Index", "Home")">Início</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index", "Servicos")">Serviços</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index", "Foto")">Fotos</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index", "Agenda")">Agenda</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index", "Contato")">Contato</a>
					</li>
				</ul>
			</div>

			<div class="collapse navbar-collapse" id="navbarNavRedes">
				<ul class="navbar-nav ms-auto">
					<li class="nav-item-rede">
						<a href="#">
							<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
								<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
							</svg>
						</a>
					</li>
					<li class="nav-item-rede">
						<a href="#">
							<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
								<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951" />
							</svg>
						</a>
					</li>
					<li class="nav-item-rede">
						<a href="#">
							<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
								<path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232" />
							</svg>
						</a>
					</li>
				</ul>
			</div>

			<div class="collapse-mobile navbar-collapse-mobile" id="navbarMenuMobile">
				<ul class="navbar-nav">
					<li class="nav-item-menu" id="menuOpen" onclick="openMenuMobile();">
						<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
							<path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5" />
						</svg>
					</li>
				</ul>
			</div>

		</div>
	</nav>

	<!-- MENU MOBILE -->
	<div class="menu-mobile" id="menu-mobile-id">
		<div class="menu-options">
			<div class="options-list">

				<ul class="navbar-nav" id="menuClose" onclick="closeMenuMobile();">
					<li class="nav-item-menu">
						<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
							<path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
						</svg>
					</li>
				</ul>

				<ul class="navbar-nav ms-auto" id="menuMobileOptions">
					<li>
						<a class="" id="mobile-link" href="@Url.Action("Index", "Home")" aria-current="page">
							Início
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
								<path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
							</svg>
						</a>
					</li>
					<li>
						<a class="" id="mobile-link" href="@Url.Action("Index", "Servicos")">
							Serviços
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
								<path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
							</svg>
						</a>
					</li>
					<li>
						<a class="" id="mobile-link" href="@Url.Action("Index", "Foto")">
							Fotos
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
								<path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
							</svg>
						</a>
					</li>
					<li>
						<a class="" id="mobile-link" href="@Url.Action("Index", "Agenda")">
							Agenda
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
								<path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
							</svg>
						</a>
					</li>
					<li>
						<a class="" id="mobile-link" href="@Url.Action("Index", "Contato")">
							Contato
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
								<path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z" />
							</svg>
						</a>
					</li>

					<li class="redes-sociais-mobile">
						<ul>
							<li>
								<a href="#">
									<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
										<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
									</svg>
								</a>
							</li>
							<li>
								<a href="#">
									<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
										<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951" />
									</svg>
								</a>
							</li>
							<li>
								<a href="#">
									<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
										<path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232" />
									</svg>
								</a>
							</li>
						</ul>
					</li>

				</ul>
			</div>
		</div>
	</div>


	<!-- HOME -->
	<div class="carousel">

		<div class="carousel-images">
			<div class="slide" style="background-image: url(../css/img/fundoApresentacao.jpeg);"></div>
			<div class="slide" style="background-image: url(../css/img/fundoApresentacao.jpeg);"></div>
			<div class="slide" style="background-image: url(../css/img/fundoApresentacao.jpeg);"></div>
			<div class="slide" style="background-image: url(../css/img/fundoApresentacao.jpeg);"></div>
			<!-- Adicione mais slides conforme necessário -->
		</div>

		<div class="carousel-text">
			<div class="txt_home mt-5">
				<div class="text-home-page">

					<h1>NOME DA CASA</h1>
					<h6>
						Texto informativo sobre o espaço em questão.
					</h6>

					<div class="mt-4">
						<div class="btn-service-row">
							<div class="btn-service">
								<a href="@Url.Action("Index", "Agenda")" class="button">
									Reserve Agora &nbsp;
									<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-arrow-right-circle-fill" viewBox="0 0 16 16">
										<path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0M4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5z" />
									</svg>
								</a>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="carousel-dots">
			<!-- Dots serão gerados dinamicamente com jQuery -->
		</div>

	</div>

	<!-- RODAPE -->
	<div class="rodape">
		<label id="txt_rodape">Copyright © 2024 – Todos os Direitos Reservados.</label>
	</div>
	
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aluguel De Casas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AluguelDeCasas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>